### ISSUE TITLE
[all components] Announce changelogs on Discord

### ISSUE THREAD

**Issue by joserodolfofreitas** [mui/mui-x#11301]
### Summary 💡

We can automatically communicate changelog to our community on Discord.

Steps:
- [ ] Create a channel on discord for release announcements
- [ ] Create Discord webhook
- [ ] Create GitHub action to post message on release

### Questions

1. Should we have a common release announcements channel or use one exclusive for X?
2. Should we mention @everyone on the server?

José: _Not everyone on the server is there for MUI X, but I'd be in favor to experiment with the mention to everyone in a specific channel for MUI X_

### Examples 🌈

![image](https://github.com/mui/mui-x/assets/550141/69e3100d-3650-460c-a15e-fd5a7b817498)

### Motivation 🔦

- helping to spread the message

**Search keywords**: release changelogs

**Comment by joserodolfofreitas** [comment]
We could use:
https://github.com/Ilshidur/action-discord

Reference:
```
name: Changelog to Discord

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Send Changelog to Discord
      uses: Ilshidur/action-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_MESSAGE: "New release: ${{ github.event.release.tag_name }}\n${{ github.event.release.body }}"
```
