### ISSUE TITLE
date picker, input field  style broken

### ISSUE THREAD

**Issue by dante01yoon** [mui/mui-x#5329]

**Comment by cherniavskii** [comment]
Hey @dante01yoon 
Can you provide a minimal example reproducing the issue?
You can start with this example: https://codesandbox.io/s/zk5n4v?file=/demo.tsx

**Comment by dante01yoon** [comment]
@cherniavskii  thank you for respond!
the reason was my app.js has `import  "./App.css"`, and has custom button styling
```css
button {
  appearance: none;
  padding: 12px;
  min-width: 200px;
  border: 0px;
  border-radius: 8px;
  cursor: pointer;
}
```

weird, should mui user not use custom element styling?
