### ISSUE TITLE
Custom pagination SCSS works fine in dev mode, but when i build the project the Datagrid restore normal pagination

### ISSUE THREAD

**Issue by sadiki-o** [mui/mui-x#7030]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1.
2.
3.

### Current behavior 😯

![AfterBuild](https://user-images.githubusercontent.com/63022311/204324747-3c3fe416-7aeb-4c81-8933-f27052cdb84c.PNG)

### Expected behavior 🤔

![InDevMode](https://user-images.githubusercontent.com/63022311/204324805-995ff102-8b21-4ea1-add7-7ec282296f4c.PNG)

### Context 🔦

i am trying to customize the footer of the Data Grid the way you can see in the expected behavior, i couldn't help but to use SCSS and customize classes to work the way i want since i found the customization part a bit hard using MUI only.

here is part of my REACT code : 
```javascript
import './pendingDocuments.scss'; 

function TablePaginationActions(props: TablePaginationActionsProps) {
  const { page } = props;

  const apiRef = useGridApiContext();
  const pageCount = useGridSelector(apiRef, gridPageCountSelector);

  return (
    <Box sx={{ flexShrink: 0, ml: 2.5 }}>
      <Pagination
        sx={{
          display: 'inline',
        }}
        color="primary"
        count={pageCount}
        page={page + 1}
        onChange={(event, value) => apiRef.current.setPage(value - 1)}
        showFirstButton
        showLastButton
      />
    </Box>
  );
}


<DataGrid
        rows={rows}
        columns={columns}
        filterModel={{
          items: [
            {
              columnField: context?.selectValue!,
              operatorValue: 'contains',
              value: context?.searchValue!,
            },
          ],
        }}
        sx={{ fontWeight: '600', fontSize: '13px' }}
        loading={rows.length === 0}
        className="max-w-[1500px]"
        autoHeight
        pageSize={pageSize}
        onPageSizeChange={(newPageSize) => setPageSize(newPageSize)}
        rowsPerPageOptions={[5, 10, 20, 50, 100]}
        disableColumnFilter
        disableColumnSelector
        disableDensitySelector
        componentsProps={{
          pagination: {
            ActionsComponent: TablePaginationActions,
          },
        }}
        localeText={frFR.components.MuiDataGrid.defaultProps.localeText}
      />
```

and here is my SCSS file:

```scss
.MuiDataGrid-footerContainer.css-17jjc08-MuiDataGrid-footerContainer > div:nth-child(1) {
  display: none !important;
}

.MuiDataGrid-footerContainer.css-17jjc08-MuiDataGrid-footerContainer {
  padding-right: 20px;

  .MuiTablePagination-root {
    width: 100% !important;
  }
  .MuiTablePagination-spacer {
    display: none;
  }
  .MuiToolbar-root {
    flex-direction: row-reverse !important;
  }

  .MuiBox-root.css-1zye22 {
    margin-right: auto;
  }

  #\:rr\: {
    order: 3;
    color: rgb(172, 169, 169);
  }

  .MuiInputBase-root.MuiInputBase-colorPrimary {
    order: 2;
    color: gray;
  }

  .MuiTablePagination-displayedRows.css-levciy-MuiTablePagination-displayedRows {
    order: 1;
    margin-left: 10px;
    color: gray;
  }

  #\:rq\: {
    background-color: #e5e6e7;
    border-radius: 4px;
  }

  .MuiBox-root.css-1zye22 {
    order: 4;
    display: flex;
    align-items: center;

    .css-1to7aaw-MuiButtonBase-root-MuiPaginationItem-root.Mui-selected {
      background-color: black;
      color: white;
    }

    .css-1to7aaw-MuiButtonBase-root-MuiPaginationItem-root {
      color: gray;
    }

    .MuiPaginationItem-firstLast,
    .MuiPaginationItem-previousNext {
      color: black;
    }
  }
}

```

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
   System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD 
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (107.0.1418.56)
  npmPackages:
    @emotion/react: ^11.10.5 => 11.10.5 
    @emotion/styled: ^11.10.5 => 11.10.5 
    @mui/base:  5.0.0-alpha.105 
    @mui/core-downloads-tracker:  5.10.13 
    @mui/icons-material: ^5.10.9 => 5.10.9 
    @mui/material: ^5.10.13 => 5.10.13 
    @mui/private-theming:  5.10.9 
    @mui/styled-engine:  5.10.8 
    @mui/system:  5.10.13 
    @mui/types:  7.2.0 
    @mui/utils:  5.10.15
    @mui/x-data-grid: ^5.17.12 => 5.17.12
    @mui/x-data-grid-generator: ^5.17.12 => 5.17.12
    @mui/x-data-grid-premium:  5.17.12
    @mui/x-data-grid-pro:  5.17.12
    @mui/x-license-pro:  5.17.12
    @types/react: ^18.0.25 => 18.0.25
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    styled-components:  5.3.6
    typescript: * => 4.9.3
```
</details>

browsers: i use Firefox and Chrome
