### ISSUE TITLE
The mui datagrid have different className for element in production and local development

### ISSUE THREAD

**Issue by pinak3748** [mui/mui-x#8007]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
I have a datagrid with the checkbox 
1.select the className and try changing the color of checkbox through css
2.test it in local it will work 
3.when you deploy the changes into the server it do not pick up the class name as it's different

### Current behavior 😯

I am customizing the datagrid as per the need which as a lot of changes in the color, alignment, and sizes. So I select the classname for the element and then overwrite it in css.

```css
.css-1pe4mpk-MuiButtonBase-root-MuiIconButton-root{
display: none !important;
}

.css-1jbbcbn-MuiDataGrid-columnHeaderTitle{
  font-family: 'Inter', 'sans-serif' !important ;
}
```

Like this but this only works on local machine, it do not work on server

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  I am using brave for development and using mui v5

```
</details>
